#!/usr/bin/env python
# -*- coding: utf-8 -*-
from TaxiFareModel.data import clean_data, get_data
from sklearn.model_selection import train_test_split
from TaxiFareModel.trainer import Trainer

# get data
# clean data
df = clean_data(get_data())

# set X and y
y = df.pop("fare_amount")
X = df

# hold out
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# create pipeline
model = Trainer(X= X_train, y=y_train)
model.set_pipeline()
# train
model.run(X_train, y_train)

# evaluate
print(f'The RMSE score of the model is: {model.evaluate(X_test, y_test)}')
